version: '3'

services: 
    weather-service:
        build: ./weather
        container_name: weather
        restart: always
        environment: 
            - APP_NAME=weather-app
        expose: 
            - 8080
        volumes: 
            - ./weather:/app
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports: 
            - "80:80"