version: '3'

services: 
    weather-service:
        build: ./server
        container_name: weather-prod
        restart: always
        ports:
            - 5000:5000
        environment: 
            - APP_NAME=weather-app
            - FLASK_ENV=production
        volumes: 
            - ./server:/app
    react:
        container_name: react
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - ./client:/app
            - /app/node_modules
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true