version: '3'

services: 
    weather-service:
        build: ./weather
        container_name: weather-prod
        restart: always
        environment: 
            - APP_NAME=weather-app
            - FLASK_ENV=production
        expose: 
            - 8080
        volumes: 
            - ./weather:/app
    nginx:
        build: ./nginx
        container_name: nginx-prod
        restart: always
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/funon.rocks.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
            - /docker-volumes/etc/letsencrypt/live/funon.rocks/fullchain.pem:/etc/letsencrypt/live/funon.rocks/fullchain.pem
            - /docker-volumes/etc/letsencrypt/live/funon.rocks/privkey.pem:/etc/letsencrypt/live/funon.rocks/privkey.pem